### ISSUE TITLE
data length is too short (data: "")

### ISSUE THREAD

**Issue by GeorgeGkinis** [logstash-plugins/logstash-output-zabbix#19]
While setting up my logstash filter I get the following error : 

**data length is too short (data: "")**

followed by logstash crashing.

The field I use as zabbix_value exists and is a string

The zabbix output part of my filter is : 

filter {
if [@metadata][http_poller] == "TreinLocatiesAging" {
    mutate {
        convert => {"[aggregations][aging][values][75.0]" => "string"}
        add_field => {
        "zabbix_host" => "NLNSVTPW001__PRD01"
        "zabbix_key" =>"ns.vt.aging.logstash"
        }
        }
 }
}

output {
    if [@metadata][http_poller] == "TreinLocatiesAging" {
        zabbix {
            zabbix_host => 'zabbix_host'
            zabbix_server_host => '127.0.0.1'
            zabbix_server_port => 10050
            zabbix_key => "zabbix_key"
            zabbix_value => "[aggregations][aging][values][75.0]"
        }
                stdout { codec => rubydebug { metadata => false}}
}
}

sample output : 
{
         "_shards" => {
             "total" => 5,
            "failed" => 0,
        "successful" => 5,
           "skipped" => 0
    },
            "hits" => {
             "hits" => [],
            "total" => 10936,
        "max_score" => 0.0
    },
            "took" => 11,
      "@timestamp" => 2017-11-20T16:01:42.724Z,
     "zabbix_host" => "NLNSVTPW001__PRD01",
        "@version" => "1",
       "timed_out" => false,
    "aggregations" => {
        "aging" => {
            "values" => {
                "75.0" => "10"
            }
        }
    },
      "zabbix_key" => "ns.vt.aging.logstash"
}

Zabbix version : 2.4.2
Logstash version : 5.6.0
Architecture is litle endian (not related to *logstash-output-zabbix plugin causes Logstash crash on Solaris (and possible other big endian platforms)* )

Logstash log : 

`[2017-11-20T15:58:47,704][INFO ][logstash.pipeline        ] Pipeline main started
[2017-11-20T15:58:47,919][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ZabbixProtocol::Error: data length is too short (data: "")>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/zabbix_protocol-0.1.5/lib/zabbix_protocol.rb:41:in `load'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-zabbix-3.0.4/lib/logstash/outputs/zabbix.rb:206:in `tcp_send'", "org/jruby/RubyIO.java:1201:in `open'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-zabbix-3.0.4/lib/logstash/outputs/zabbix.rb:203:in `tcp_send'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-zabbix-3.0.4/lib/logstash/outputs/zabbix.rb:226:in `send_to_zabbix'", "org/jruby/ext/timeout/Timeout.java:115:in `timeout'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-zabbix-3.0.4/lib/logstash/outputs/zabbix.rb:225:in `send_to_zabbix'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-zabbix-3.0.4/lib/logstash/outputs/zabbix.rb:242:in `receive'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:22:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:49:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:436:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:435:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:381:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}`

**Comment by pkaramol** [comment]
@GeorgeGkinis have you managed to work this out? cause I am facing the same issue. I am actually hard coding the value to be certain it exists for testing.

**Comment by baptistecdr** [comment]
Sorry for bumping this issue.
I had the same issue and the connection to the Zabbix server couldn't be made which provoke this error.
