### ISSUE TITLE
Posting data to zabbix fails with data too short

### ISSUE THREAD

**Issue by pkaramol** [logstash-plugins/logstash-output-zabbix#21]
Using `logstash 6.4.2`

- Version: 
```
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems# ls | grep zabb
logstash-output-zabbix-3.0.5
zabbix_protocol-0.1.5
```

- Operating System:
```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

In a `filter`:

```
	if "paloalto" in [tags] {
		metrics {
      		meter => "events_paloalto"
      		flush_interval => 30
      		add_tag => "metric_paloalto"
					add_field => [ "[@metadata][zabbix_host]", "my-logstash-host" ]
					add_field => [ "[@metadata][zabbix_key]", "paloalto_rate_1m" ]
					add_field => [ "[@metadata][zabbix_value]", "10000" ]
  		}
	}

```

In my `output`

      zabbix {
        zabbix_host => "[@metadata][zabbix_host]"
        zabbix_key => "[@metadata][zabbix_key]"
        zabbix_value => "[@metadata][zabbix_value]"
        zabbix_server_host => "my-zabbix-server"
        zabbix_server_port => 10050
        timeout => 7
        # zabbix_value => "[events_paloalto]][rate_1m]"
      }

In my `logstash` logs

```
[2019-01-31T14:41:01,012][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ZabbixProtocol::Error: data length is too short (data: "")>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/zabbix_protocol-0.1.5/lib/zabbix_protocol.rb:41:in `load'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-zabbix-3.0.5/lib/logstash/outputs/zabbix.rb:206:in `block in tcp_send'", "org/jruby/RubyIO.java:1156:in `open'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-zabbix-3.0.5/lib/logstash/outputs/zabbix.rb:203:in `tcp_send'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-zabbix-3.0.5/lib/logstash/outputs/zabbix.rb:226:in `block in send_to_zabbix'", "org/jruby/ext/timeout/Timeout.java:117:in `timeout'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-zabbix-3.0.5/lib/logstash/outputs/zabbix.rb:225:in `send_to_zabbix'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-zabbix-3.0.5/lib/logstash/outputs/zabbix.rb:242:in `receive'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:89:in `block in multi_receive'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:89:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:114:in `multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:97:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:373:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:372:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:324:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:286:in `block in start_workers'"]}
[2019-01-31T14:41:01,189][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
```

**Comment by xemina** [comment]
I have the same problem did you solve it？
